project:
  type: website

website:
  favicon: "🐱"
  title: "Magdelyn Herzig"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About
  page-footer:
    left: "© Magdelyn Herzig"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false


